# Generated by Django 5.1 on 2024-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signals_count', models.IntegerField()),
                ('info_count', models.IntegerField()),
            ],
        ),
    ]
